# This is an workflow that is able to print the structure of the directory.
# Trigger: Push event
# Input: 
# Output: Printing of the directory structure

# The name of the workflow
name: Print directory structure

# The decription of the action
description: This is an action that is able to print the stucture of the directories present in the repository at the moment of execution. 

# Action icon and color
branding:
  icon: 'box'  
  color: 'blue'

runs:
  using: "composite"
    # Steps that will be executed as part of the job
  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2
      
    - name: Print directory structure
      shell: bash
      run: |
          echo " alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'" " > printTree.zshrc
          tree
      
